CARE_CHECKLIST_ITEMS = (
    ("appetite", "Khẩu vị và lượng thức ăn"),
    ("water", "Nước uống sạch và đủ"),
    ("feeding_schedule", "Đúng giờ và đúng khẩu phần"),
    ("weight", "Cân nặng và biến động cân nặng"),
    ("body_condition", "Thể trạng và ngoại hình"),
    ("coat_skin", "Da, lông hoặc lớp phủ cơ thể"),
    ("eyes", "Mắt và dấu hiệu tiết dịch"),
    ("ears", "Tai và dấu hiệu viêm/nhiễm bẩn"),
    ("nose_breathing", "Mũi và nhịp thở"),
    ("mouth_teeth", "Miệng, răng và nướu"),
    ("movement", "Vận động và dáng đi"),
    ("droppings", "Phân, nước tiểu và bài tiết"),
    ("temperature", "Nhiệt độ (nếu cần theo dõi)"),
    ("behavior", "Hành vi và mức độ tỉnh táo"),
    ("stress", "Dấu hiệu căng thẳng hoặc sợ hãi"),
    ("social", "Tương tác với người và con vật khác"),
    ("sleep", "Giấc ngủ và thời gian nghỉ ngơi"),
    ("enclosure_cleanliness", "Vệ sinh chuồng/khu vực ở"),
    ("enclosure_safety", "An toàn, khóa cửa và vật nguy hiểm"),
    ("enclosure_space", "Không gian và mật độ nuôi"),
    ("ventilation", "Thông thoáng và chất lượng không khí"),
    ("temperature_humidity", "Nhiệt độ, độ ẩm môi trường"),
    ("vaccination", "Tình trạng và lịch tiêm phòng"),
    ("parasite_control", "Phòng/ký sinh trùng và lịch tẩy giun"),
    ("medication", "Thuốc, liều dùng và lịch tái khám"),
)

CARE_CHECKLIST_STATUSES = ("OK", "NEEDS_ATTENTION", "NOT_APPLICABLE")
