"""Reference data for common dog and cat breeds.

This catalog stores breed-level metadata used by the pet management system,
including the country and region of origin, climate suitability, housing
conditions, exercise level, and other husbandry considerations.
"""

from __future__ import annotations

BREED_CATALOG: list[dict[str, str]] = [
    {
        "species": "Chó",
        "breed_name": "Golden Retriever",
        "breed_name_en": "Golden Retriever",
        "origin_country": "United Kingdom",
        "origin_region": "Scotland",
        "climate": "Ôn đới / mát",
        "suitable_environment": "Nhà có sân, căn hộ nếu được vận động đủ",
        "exercise_level": "Cao",
        "heat_tolerance": "Trung bình",
        "cold_tolerance": "Khá",
        "size": "Lớn",
        "adult_weight_kg": "25-34",
        "lifespan_years": "10-12",
        "suitable_home": "Nhà riêng, sân vườn, người chủ hoạt động đều",
    },
    {
        "species": "Chó",
        "breed_name": "Labrador Retriever",
        "breed_name_en": "Labrador Retriever",
        "origin_country": "Canada",
        "origin_region": "Newfoundland",
        "climate": "Ôn đới / mát",
        "suitable_environment": "Nhà có sân, có thể sống ở căn hộ nếu vận động đều",
        "exercise_level": "Cao",
        "heat_tolerance": "Khá",
        "cold_tolerance": "Khá",
        "size": "Lớn",
        "adult_weight_kg": "25-36",
        "lifespan_years": "10-13",
        "suitable_home": "Gia đình năng động, có thời gian đi dạo và chơi",
    },
    {
        "species": "Chó",
        "breed_name": "German Shepherd",
        "breed_name_en": "German Shepherd",
        "origin_country": "Germany",
        "origin_region": "Đức",
        "climate": "Ôn đới / mát",
        "suitable_environment": "Nhà rộng, có sân, tránh sống chật chội",
        "exercise_level": "Cao",
        "heat_tolerance": "Trung bình",
        "cold_tolerance": "Khá",
        "size": "Lớn",
        "adult_weight_kg": "22-40",
        "lifespan_years": "9-13",
        "suitable_home": "Gia đình có thể tập huấn và vận động đều",
    },
    {
        "species": "Chó",
        "breed_name": "Poodle",
        "breed_name_en": "Poodle",
        "origin_country": "France",
        "origin_region": "Tây Âu",
        "climate": "Ôn đới / mát",
        "suitable_environment": "Căn hộ hoặc nhà có không gian vận động",
        "exercise_level": "Trung bình - cao",
        "heat_tolerance": "Khá",
        "cold_tolerance": "Khá",
        "size": "Vừa - lớn",
        "adult_weight_kg": "4-30",
        "lifespan_years": "12-15",
        "suitable_home": "Người chủ thích chăm sóc lông và vận động đều",
    },
    {
        "species": "Chó",
        "breed_name": "French Bulldog",
        "breed_name_en": "French Bulldog",
        "origin_country": "France",
        "origin_region": "Pháp",
        "climate": "Mát / ấm",
        "suitable_environment": "Trong nhà, tránh nhiệt độ quá cao",
        "exercise_level": "Thấp - trung bình",
        "heat_tolerance": "Thấp",
        "cold_tolerance": "Trung bình",
        "size": "Vừa",
        "adult_weight_kg": "10-13",
        "lifespan_years": "10-12",
        "suitable_home": "Căn hộ hoặc nhà nhỏ, chủ thích thú cưng dễ chăm",
    },
    {
        "species": "Chó",
        "breed_name": "Pomeranian",
        "breed_name_en": "Pomeranian",
        "origin_country": "Germany",
        "origin_region": "Pomerania",
        "climate": "Mát / ôn đới",
        "suitable_environment": "Trong nhà, cần không gian thoải mái",
        "exercise_level": "Trung bình",
        "heat_tolerance": "Trung bình",
        "cold_tolerance": "Khá",
        "size": "Nhỏ",
        "adult_weight_kg": "1.5-3.5",
        "lifespan_years": "12-16",
        "suitable_home": "Chủ ở nội thành hoặc căn hộ, dễ mang theo",
    },
    {
        "species": "Chó",
        "breed_name": "Chihuahua",
        "breed_name_en": "Chihuahua",
        "origin_country": "Mexico",
        "origin_region": "Mexico",
        "climate": "Ấm / khô",
        "suitable_environment": "Trong nhà, tránh gió lạnh kéo dài",
        "exercise_level": "Thấp - trung bình",
        "heat_tolerance": "Khá",
        "cold_tolerance": "Thấp",
        "size": "Rất nhỏ",
        "adult_weight_kg": "1-3",
        "lifespan_years": "12-20",
        "suitable_home": "Căn hộ, chủ dành nhiều thời gian trong nhà",
    },
    {
        "species": "Chó",
        "breed_name": "Shiba Inu",
        "breed_name_en": "Shiba Inu",
        "origin_country": "Japan",
        "origin_region": "Nhật Bản",
        "climate": "Ôn đới / mát",
        "suitable_environment": "Nhà có sân hoặc không gian vận động đều",
        "exercise_level": "Trung bình - cao",
        "heat_tolerance": "Khá",
        "cold_tolerance": "Khá",
        "size": "Vừa",
        "adult_weight_kg": "8-11",
        "lifespan_years": "12-15",
        "suitable_home": "Chủ tập trung huấn luyện và vận động đều",
    },
    {
        "species": "Chó",
        "breed_name": "Akita Inu",
        "breed_name_en": "Akita Inu",
        "origin_country": "Japan",
        "origin_region": "Nhật Bản",
        "climate": "Mát / lạnh",
        "suitable_environment": "Nhà rộng, không gian thoáng, tránh nóng kéo dài",
        "exercise_level": "Trung bình - cao",
        "heat_tolerance": "Trung bình",
        "cold_tolerance": "Khá",
        "size": "Lớn",
        "adult_weight_kg": "30-50",
        "lifespan_years": "10-15",
        "suitable_home": "Nhà có sân, người chủ có kinh nghiệm với chó lớn",
    },
    {
        "species": "Chó",
        "breed_name": "Siberian Husky",
        "breed_name_en": "Siberian Husky",
        "origin_country": "Russia",
        "origin_region": "Siberia",
        "climate": "Lạnh / mát",
        "suitable_environment": "Nhà rộng, sân thoáng, cần vận động nhiều",
        "exercise_level": "Cao",
        "heat_tolerance": "Thấp",
        "cold_tolerance": "Rất cao",
        "size": "Lớn",
        "adult_weight_kg": "16-27",
        "lifespan_years": "12-14",
        "suitable_home": "Người chủ năng động, có không gian ngoài trời",
    },
    {
        "species": "Chó",
        "breed_name": "Alaskan Malamute",
        "breed_name_en": "Alaskan Malamute",
        "origin_country": "United States",
        "origin_region": "Alaska",
        "climate": "Lạnh / mát",
        "suitable_environment": "Nhà rộng, sân thoáng, không thích nắng nóng kéo dài",
        "exercise_level": "Cao",
        "heat_tolerance": "Thấp",
        "cold_tolerance": "Rất cao",
        "size": "Lớn",
        "adult_weight_kg": "24-40",
        "lifespan_years": "10-14",
        "suitable_home": "Không gian rộng, chủ có kinh nghiệm",
    },
    {
        "species": "Chó",
        "breed_name": "Dachshund",
        "breed_name_en": "Dachshund",
        "origin_country": "Germany",
        "origin_region": "Đức",
        "climate": "Ôn đới / mát",
        "suitable_environment": "Nhà/căn hộ, cần không gian ngủ ấm",
        "exercise_level": "Trung bình",
        "heat_tolerance": "Trung bình",
        "cold_tolerance": "Khá",
        "size": "Vừa",
        "adult_weight_kg": "4-9",
        "lifespan_years": "12-16",
        "suitable_home": "Gia đình thích chó nhỏ, dễ nuôi trong nhà",
    },
    {
        "species": "Chó",
        "breed_name": "Corgi",
        "breed_name_en": "Corgi",
        "origin_country": "United Kingdom",
        "origin_region": "Wales",
        "climate": "Ôn đới / mát",
        "suitable_environment": "Nhà/căn hộ, thích có sân hoặc không gian đi bộ",
        "exercise_level": "Cao",
        "heat_tolerance": "Trung bình",
        "cold_tolerance": "Khá",
        "size": "Vừa",
        "adult_weight_kg": "10-15",
        "lifespan_years": "12-15",
        "suitable_home": "Chủ năng động, thích chó lanh lợi và hoạt động",
    },
    {
        "species": "Chó",
        "breed_name": "Beagle",
        "breed_name_en": "Beagle",
        "origin_country": "United Kingdom",
        "origin_region": "Anh",
        "climate": "Ôn đới / mát",
        "suitable_environment": "Nhà có sân, cần đi bộ và thăm thú",
        "exercise_level": "Cao",
        "heat_tolerance": "Khá",
        "cold_tolerance": "Khá",
        "size": "Vừa",
        "adult_weight_kg": "9-11",
        "lifespan_years": "10-15",
        "suitable_home": "Gia đình năng động, có thời gian đi lại và trò chơi",
    },
    {
        "species": "Chó",
        "breed_name": "Rottweiler",
        "breed_name_en": "Rottweiler",
        "origin_country": "Germany",
        "origin_region": "Đức",
        "climate": "Ôn đới / mát",
        "suitable_environment": "Nhà rộng, sân thoáng, cần huấn luyện kỷ luật",
        "exercise_level": "Cao",
        "heat_tolerance": "Trung bình",
        "cold_tolerance": "Khá",
        "size": "Lớn",
        "adult_weight_kg": "35-60",
        "lifespan_years": "8-10",
        "suitable_home": "Người chủ có kinh nghiệm và kiểm soát tốt",
    },
    {
        "species": "Chó",
        "breed_name": "Doberman",
        "breed_name_en": "Doberman",
        "origin_country": "Germany",
        "origin_region": "Đức",
        "climate": "Ôn đới / mát",
        "suitable_environment": "Nhà rộng, không gian vận động và huấn luyện",
        "exercise_level": "Cao",
        "heat_tolerance": "Trung bình",
        "cold_tolerance": "Khá",
        "size": "Lớn",
        "adult_weight_kg": "30-45",
        "lifespan_years": "10-12",
        "suitable_home": "Chủ có lối sống đều, có thể huấn luyện thường xuyên",
    },
    {
        "species": "Chó",
        "breed_name": "Border Collie",
        "breed_name_en": "Border Collie",
        "origin_country": "United Kingdom",
        "origin_region": "Scotland",
        "climate": "Mát / ôn đới",
        "suitable_environment": "Nhà rộng, sân, cần hoạt động và công việc",
        "exercise_level": "Rất cao",
        "heat_tolerance": "Trung bình",
        "cold_tolerance": "Khá",
        "size": "Vừa - lớn",
        "adult_weight_kg": "14-20",
        "lifespan_years": "10-14",
        "suitable_home": "Gia đình năng động, có thể cho chạy, tập luyện",
    },
    {
        "species": "Chó",
        "breed_name": "Yorkshire Terrier",
        "breed_name_en": "Yorkshire Terrier",
        "origin_country": "United Kingdom",
        "origin_region": "Yorkshire",
        "climate": "Ôn đới / mát",
        "suitable_environment": "Trong nhà, dễ sống ở căn hộ",
        "exercise_level": "Thấp - trung bình",
        "heat_tolerance": "Khá",
        "cold_tolerance": "Khá",
        "size": "Nhỏ",
        "adult_weight_kg": "2-3",
        "lifespan_years": "11-15",
        "suitable_home": "Căn hộ, người chủ yêu thích chó nhỏ, dễ chăm",
    },
    {
        "species": "Chó",
        "breed_name": "Maltese",
        "breed_name_en": "Maltese",
        "origin_country": "Italy",
        "origin_region": "Địa Trung Hải",
        "climate": "Ấm / mát",
        "suitable_environment": "Trong nhà, cần giữ ấm khi thời tiết lạnh",
        "exercise_level": "Thấp - trung bình",
        "heat_tolerance": "Khá",
        "cold_tolerance": "Trung bình",
        "size": "Nhỏ",
        "adult_weight_kg": "2-4",
        "lifespan_years": "12-15",
        "suitable_home": "Chủ ở nhà nhiều, thích thú cưng thân thiện",
    },
    {
        "species": "Chó",
        "breed_name": "Shih Tzu",
        "breed_name_en": "Shih Tzu",
        "origin_country": "China",
        "origin_region": "Tây Tạng / Trung Quốc",
        "climate": "Mát / ôn đới",
        "suitable_environment": "Trong nhà, thích điều kiện ấm và kín",
        "exercise_level": "Thấp - trung bình",
        "heat_tolerance": "Khá",
        "cold_tolerance": "Trung bình",
        "size": "Nhỏ",
        "adult_weight_kg": "4-7",
        "lifespan_years": "10-16",
        "suitable_home": "Căn hộ, người chủ muốn thú cưng dễ nuôi",
    },
    {
        "species": "Chó",
        "breed_name": "Chow Chow",
        "breed_name_en": "Chow Chow",
        "origin_country": "China",
        "origin_region": "Bắc Trung Quốc",
        "climate": "Mát / lạnh",
        "suitable_environment": "Nhà thoáng, không ưa nắng nóng dài ngày",
        "exercise_level": "Trung bình",
        "heat_tolerance": "Trung bình",
        "cold_tolerance": "Khá",
        "size": "Vừa - lớn",
        "adult_weight_kg": "18-32",
        "lifespan_years": "9-15",
        "suitable_home": "Nhà có không gian riêng, chăm sóc lông kỹ",
    },
    {
        "species": "Chó",
        "breed_name": "Samoyed",
        "breed_name_en": "Samoyed",
        "origin_country": "Russia",
        "origin_region": "Siberia",
        "climate": "Lạnh / mát",
        "suitable_environment": "Có không gian rộng, không thích nhiệt độ cao",
        "exercise_level": "Cao",
        "heat_tolerance": "Thấp",
        "cold_tolerance": "Rất cao",
        "size": "Lớn",
        "adult_weight_kg": "20-30",
        "lifespan_years": "12-14",
        "suitable_home": "Chủ có không gian ngoài trời, thích chó hoạt động",
    },
    {
        "species": "Chó",
        "breed_name": "Great Dane",
        "breed_name_en": "Great Dane",
        "origin_country": "Germany",
        "origin_region": "Đức",
        "climate": "Ôn đới / mát",
        "suitable_environment": "Nhà rộng, sân thoáng, tránh nóng kéo dài",
        "exercise_level": "Trung bình",
        "heat_tolerance": "Trung bình",
        "cold_tolerance": "Khá",
        "size": "Rất lớn",
        "adult_weight_kg": "45-90",
        "lifespan_years": "7-10",
        "suitable_home": "Nhà rộng, người chủ có kinh nghiệm chó lớn",
    },
    {
        "species": "Chó",
        "breed_name": "Saint Bernard",
        "breed_name_en": "Saint Bernard",
        "origin_country": "Switzerland",
        "origin_region": "Alps",
        "climate": "Lạnh / mát",
        "suitable_environment": "Nhà rộng, không gian thoáng, giữ ấm",
        "exercise_level": "Trung bình",
        "heat_tolerance": "Thấp",
        "cold_tolerance": "Rất cao",
        "size": "Rất lớn",
        "adult_weight_kg": "55-90",
        "lifespan_years": "8-10",
        "suitable_home": "Không gian rộng, có thời gian chăm sóc và vận động",
    },
    {
        "species": "Mèo",
        "breed_name": "British Shorthair",
        "breed_name_en": "British Shorthair",
        "origin_country": "United Kingdom",
        "origin_region": "Anh",
        "climate": "Mát / ôn đới",
        "suitable_environment": "Trong nhà, dễ sống ở căn hộ hoặc nhà",
        "exercise_level": "Thấp - trung bình",
        "heat_tolerance": "Khá",
        "cold_tolerance": "Khá",
        "size": "Vừa",
        "adult_weight_kg": "4-8",
        "lifespan_years": "12-17",
        "suitable_home": "Chủ muốn mèo dễ tính, ít quấy rầy, phù hợp nhà ở",
    },
    {
        "species": "Mèo",
        "breed_name": "Scottish Fold",
        "breed_name_en": "Scottish Fold",
        "origin_country": "United Kingdom",
        "origin_region": "Scotland",
        "climate": "Mát / ôn đới",
        "suitable_environment": "Trong nhà, cần môi trường ấm và yên tĩnh",
        "exercise_level": "Thấp - trung bình",
        "heat_tolerance": "Khá",
        "cold_tolerance": "Khá",
        "size": "Vừa",
        "adult_weight_kg": "3-7",
        "lifespan_years": "12-15",
        "suitable_home": "Nhà ở, chủ yêu thích mèo hiền, thân thiện",
    },
    {
        "species": "Mèo",
        "breed_name": "Persian",
        "breed_name_en": "Persian",
        "origin_country": "Iran",
        "origin_region": "Ba Tư",
        "climate": "Mát / ôn đới",
        "suitable_environment": "Trong nhà, cần không gian yên tĩnh và sạch",
        "exercise_level": "Thấp",
        "heat_tolerance": "Khá",
        "cold_tolerance": "Khá",
        "size": "Vừa - lớn",
        "adult_weight_kg": "3-7",
        "lifespan_years": "12-18",
        "suitable_home": "Chủ thích mèo lông dài, dễ sống trong nhà",
    },
    {
        "species": "Mèo",
        "breed_name": "Maine Coon",
        "breed_name_en": "Maine Coon",
        "origin_country": "United States",
        "origin_region": "Maine",
        "climate": "Mát / lạnh",
        "suitable_environment": "Nhà rộng, thích không gian sống thoáng",
        "exercise_level": "Trung bình",
        "heat_tolerance": "Trung bình",
        "cold_tolerance": "Khá",
        "size": "Lớn",
        "adult_weight_kg": "5-9",
        "lifespan_years": "10-15",
        "suitable_home": "Gia đình có không gian rộng và thích mèo thân thiện",
    },
    {
        "species": "Mèo",
        "breed_name": "Ragdoll",
        "breed_name_en": "Ragdoll",
        "origin_country": "United States",
        "origin_region": "California",
        "climate": "Ôn đới / mát",
        "suitable_environment": "Trong nhà, cần không gian thoải mái và thân thiện",
        "exercise_level": "Thấp - trung bình",
        "heat_tolerance": "Khá",
        "cold_tolerance": "Khá",
        "size": "Lớn",
        "adult_weight_kg": "4-9",
        "lifespan_years": "12-18",
        "suitable_home": "Gia đình yêu thích mèo hiền và dễ gần",
    },
    {
        "species": "Mèo",
        "breed_name": "Siamese",
        "breed_name_en": "Siamese",
        "origin_country": "Thailand",
        "origin_region": "Thái Lan",
        "climate": "Ấm / mát",
        "suitable_environment": "Trong nhà, cần môi trường an toàn và gần chủ",
        "exercise_level": "Trung bình",
        "heat_tolerance": "Khá",
        "cold_tolerance": "Trung bình",
        "size": "Vừa",
        "adult_weight_kg": "3-6",
        "lifespan_years": "10-15",
        "suitable_home": "Chủ ở nhà nhiều, thích mèo năng động và vui vẻ",
    },
    {
        "species": "Mèo",
        "breed_name": "Bengal",
        "breed_name_en": "Bengal",
        "origin_country": "United States",
        "origin_region": "Mỹ",
        "climate": "Ấm / ôn đới",
        "suitable_environment": "Trong nhà, cần nhiều hoạt động và đồ chơi",
        "exercise_level": "Cao",
        "heat_tolerance": "Khá",
        "cold_tolerance": "Trung bình",
        "size": "Vừa - lớn",
        "adult_weight_kg": "4-8",
        "lifespan_years": "10-15",
        "suitable_home": "Mèo năng động, chủ thích tương tác và khám phá",
    },
    {
        "species": "Mèo",
        "breed_name": "Sphynx",
        "breed_name_en": "Sphynx",
        "origin_country": "Canada",
        "origin_region": "Canada",
        "climate": "Ấm / mát",
        "suitable_environment": "Trong nhà, cần giữ ấm và tránh gió lạnh",
        "exercise_level": "Trung bình",
        "heat_tolerance": "Khá",
        "cold_tolerance": "Trung bình",
        "size": "Vừa",
        "adult_weight_kg": "3-6",
        "lifespan_years": "10-14",
        "suitable_home": "Chủ đầu tư chăm sóc da và nhiệt độ phòng tốt",
    },
    {
        "species": "Mèo",
        "breed_name": "Russian Blue",
        "breed_name_en": "Russian Blue",
        "origin_country": "Russia",
        "origin_region": "Nga",
        "climate": "Mát / lạnh",
        "suitable_environment": "Trong nhà, cần sạch và yên tĩnh",
        "exercise_level": "Thấp - trung bình",
        "heat_tolerance": "Trung bình",
        "cold_tolerance": "Khá",
        "size": "Vừa",
        "adult_weight_kg": "3-6",
        "lifespan_years": "10-15",
        "suitable_home": "Chủ muốn mèo mềm mại, ít quấy rầy, dễ nuôi",
    },
    {
        "species": "Mèo",
        "breed_name": "Norwegian Forest",
        "breed_name_en": "Norwegian Forest Cat",
        "origin_country": "Norway",
        "origin_region": "Na Uy",
        "climate": "Lạnh / mát",
        "suitable_environment": "Nhà thoáng, không gian rộng và lông dày",
        "exercise_level": "Trung bình",
        "heat_tolerance": "Thấp",
        "cold_tolerance": "Rất cao",
        "size": "Lớn",
        "adult_weight_kg": "4-8",
        "lifespan_years": "12-16",
        "suitable_home": "Nhà có không gian rộng, chủ thích mèo có lông dày",
    },
    {
        "species": "Mèo",
        "breed_name": "Birman",
        "breed_name_en": "Birman",
        "origin_country": "Myanmar",
        "origin_region": "Myanmar / Pháp",
        "climate": "Ấm / mát",
        "suitable_environment": "Trong nhà, cần không gian thoải mái và vui vẻ",
        "exercise_level": "Thấp - trung bình",
        "heat_tolerance": "Khá",
        "cold_tolerance": "Khá",
        "size": "Vừa - lớn",
        "adult_weight_kg": "3-7",
        "lifespan_years": "10-15",
        "suitable_home": "Chủ muốn mèo hiền, thân thiện và dễ hòa nhập",
    },
    {
        "species": "Mèo",
        "breed_name": "Abyssinian",
        "breed_name_en": "Abyssinian",
        "origin_country": "Ethiopia",
        "origin_region": "Đông Bắc Phi",
        "climate": "Ấm / ôn đới",
        "suitable_environment": "Trong nhà, cần tương tác và đồ chơi",
        "exercise_level": "Cao",
        "heat_tolerance": "Khá",
        "cold_tolerance": "Trung bình",
        "size": "Vừa",
        "adult_weight_kg": "3-5",
        "lifespan_years": "9-15",
        "suitable_home": "Chủ năng động, thích mèo lang thang, hiếu động",
    },
    {
        "species": "Mèo",
        "breed_name": "American Shorthair",
        "breed_name_en": "American Shorthair",
        "origin_country": "United States",
        "origin_region": "Mỹ",
        "climate": "Ôn đới / mát",
        "suitable_environment": "Trong nhà, dễ thích nghi với nhiều môi trường",
        "exercise_level": "Trung bình",
        "heat_tolerance": "Khá",
        "cold_tolerance": "Khá",
        "size": "Vừa",
        "adult_weight_kg": "3-6",
        "lifespan_years": "12-15",
        "suitable_home": "Gia đình mong muốn mèo khỏe mạnh, dễ nuôi",
    },
    {
        "species": "Mèo",
        "breed_name": "Exotic Shorthair",
        "breed_name_en": "Exotic Shorthair",
        "origin_country": "United States",
        "origin_region": "Mỹ",
        "climate": "Mát / ôn đới",
        "suitable_environment": "Trong nhà, thích môi trường yên tĩnh",
        "exercise_level": "Thấp - trung bình",
        "heat_tolerance": "Khá",
        "cold_tolerance": "Khá",
        "size": "Vừa",
        "adult_weight_kg": "3-6",
        "lifespan_years": "10-15",
        "suitable_home": "Chủ muốn mèo lông ngắn, hiền và dễ chăm",
    },
    {
        "species": "Mèo",
        "breed_name": "Turkish Angora",
        "breed_name_en": "Turkish Angora",
        "origin_country": "Turkey",
        "origin_region": "Ankara",
        "climate": "Ôn đới / mát",
        "suitable_environment": "Trong nhà, cần không gian vận động nhẹ",
        "exercise_level": "Trung bình",
        "heat_tolerance": "Khá",
        "cold_tolerance": "Khá",
        "size": "Vừa",
        "adult_weight_kg": "3-5",
        "lifespan_years": "12-18",
        "suitable_home": "Chủ thích mèo lông dài, trông rất đẹp và hoạt động",
    },
    {
        "species": "Mèo",
        "breed_name": "Turkish Van",
        "breed_name_en": "Turkish Van",
        "origin_country": "Turkey",
        "origin_region": "Vùng hồ Van",
        "climate": "Ôn đới / mát",
        "suitable_environment": "Nhà thoáng, có không gian đi lại và chơi",
        "exercise_level": "Trung bình",
        "heat_tolerance": "Khá",
        "cold_tolerance": "Khá",
        "size": "Vừa",
        "adult_weight_kg": "3-7",
        "lifespan_years": "12-17",
        "suitable_home": "Chủ thích mèo thể thao, thích nước và vận động",
    },
    {
        "species": "Mèo",
        "breed_name": "Oriental Shorthair",
        "breed_name_en": "Oriental Shorthair",
        "origin_country": "United Kingdom",
        "origin_region": "Anh",
        "climate": "Ấm / ôn đới",
        "suitable_environment": "Trong nhà, cần tương tác và hoạt động thường xuyên",
        "exercise_level": "Trung bình - cao",
        "heat_tolerance": "Khá",
        "cold_tolerance": "Trung bình",
        "size": "Vừa",
        "adult_weight_kg": "3-5",
        "lifespan_years": "10-15",
        "suitable_home": "Người chủ thích mèo năng động, nhạy bén",
    },
    {
        "species": "Mèo",
        "breed_name": "Burmese",
        "breed_name_en": "Burmese",
        "origin_country": "Thailand",
        "origin_region": "Đông Nam Á",
        "climate": "Ấm / mát",
        "suitable_environment": "Trong nhà, gần chủ, cần tương tác",
        "exercise_level": "Trung bình",
        "heat_tolerance": "Khá",
        "cold_tolerance": "Trung bình",
        "size": "Vừa",
        "adult_weight_kg": "3-6",
        "lifespan_years": "10-16",
        "suitable_home": "Chủ có thời gian quan tâm, mèo hướng con người",
    },
    {
        "species": "Mèo",
        "breed_name": "Devon Rex",
        "breed_name_en": "Devon Rex",
        "origin_country": "United Kingdom",
        "origin_region": "Devon",
        "climate": "Mát / ôn đới",
        "suitable_environment": "Trong nhà, cần giữ ấm trong mùa lạnh",
        "exercise_level": "Trung bình",
        "heat_tolerance": "Khá",
        "cold_tolerance": "Khá",
        "size": "Vừa",
        "adult_weight_kg": "2-4",
        "lifespan_years": "10-15",
        "suitable_home": "Chủ thích mèo lông ngắn, mềm và thân thiện",
    },
    {
        "species": "Mèo",
        "breed_name": "Cornish Rex",
        "breed_name_en": "Cornish Rex",
        "origin_country": "United Kingdom",
        "origin_region": "Cornwall",
        "climate": "Mát / ôn đới",
        "suitable_environment": "Trong nhà, cần điều kiện ấm và yên tĩnh",
        "exercise_level": "Trung bình",
        "heat_tolerance": "Khá",
        "cold_tolerance": "Khá",
        "size": "Vừa",
        "adult_weight_kg": "2-5",
        "lifespan_years": "10-15",
        "suitable_home": "Người chủ muốn mèo nhạy cảm, dễ gần, hoạt động",
    },
]

BREED_CATALOG_BY_SPECIES: dict[str, list[dict[str, str]]] = {
    "Chó": [breed for breed in BREED_CATALOG if breed["species"] == "Chó"],
    "Mèo": [breed for breed in BREED_CATALOG if breed["species"] == "Mèo"],
}
