ANIMAL_STATUSES = (
    "PENDING_INSPECTION",
    "AVAILABLE",
    "RESERVED",
    "SOLD",
    "QUARANTINE",
    "TREATMENT",
    "TRANSFERRED",
    "DECEASED",
)

ANIMAL_PROFILE_FIELDS = (
    "animal_code",
    "name",
    "species",
    "breed",
    "gender",
    "birth_date",
    "color",
    "weight",
    "origin",
    "purchase_price",
    "sale_price",
    "status",
    "health_status",
    "description",
    "supplier_name",
    "intake_date",
    "microchip_id",
    "cage_location",
    "diet",
    "feeding_schedule",
    "allergies",
    "vaccination_status",
    "last_vet_visit",
    "exercise_needs",
    "behavior",
)
