import csv
import json
from pathlib import Path

root = Path(__file__).resolve().parent
out_dir = root / "exports"
out_dir.mkdir(parents=True, exist_ok=True)

DOGS = [
    ("Golden Retriever", "United Kingdom", "Scotland", "Ôn đới / mát", "Nhà có sân, căn hộ nếu vận động đủ", "15-26", "Large", "25-34", "10-12", "Cao", "Rất cao", "Gà, cá, bò", "Hạt, pate, mousse", "Gà, cá", "Jerky, dental", "Hạt puppy large breed", "Hạt adult active", "Hạt senior joint support", "Nhà có sân"),
    ("Labrador Retriever", "Canada", "Newfoundland", "Ôn đới / mát", "Nhà có sân hoặc căn hộ nếu vận động đều", "15-26", "Large", "25-36", "10-13", "Cao", "Rất cao", "Gà, bò, cá", "Hạt, pate, wet", "Gà, bò", "Jerky, chew", "Hạt puppy high energy", "Hạt adult active", "Hạt senior weight control", "Nhà có sân"),
    ("German Shepherd", "Germany", "Đức", "Ôn đới / mát", "Nhà rộng, sân, không gian vận động", "10-24", "Large", "22-40", "9-13", "Cao", "Rất cao", "Bò, gà, cừu", "Hạt, pate, wet", "Bò, gà", "Jerky, dental", "Hạt puppy large breed", "Hạt adult working breed", "Hạt senior joint care", "Nhà rộng"),
    ("Poodle", "France", "Tây Âu", "Ôn đới / mát", "Căn hộ hoặc nhà có vận động", "10-24", "Medium/Large", "4-30", "12-15", "Trung bình - cao", "Cao", "Gà, cá, vịt", "Hạt, pate, mousse", "Gà, cá", "Jerky, freeze-dried", "Hạt puppy mini/medium", "Hạt adult quality protein", "Hạt senior coat care", "Nhà/căn hộ"),
    ("French Bulldog", "France", "Pháp", "Mát / ấm", "Trong nhà, tránh nóng kéo dài", "18-27", "Small/Medium", "10-13", "10-12", "Trung bình", "Trung bình", "Gà, cá, vịt", "Hạt, wet, pate", "Gà, cá", "Soft treat, dental", "Hạt puppy small breed", "Hạt adult easy digest", "Hạt senior low-impact", "Trong nhà"),
    ("Pomeranian", "Germany", "Pomerania", "Mát / ôn đới", "Trong nhà, không gian ấm", "15-24", "Toy", "1.5-3.5", "12-16", "Trung bình", "Trung bình", "Gà, cá", "Hạt, soft food", "Gà, cá", "Mini chew", "Hạt puppy toy breed", "Hạt adult small breed", "Hạt senior low calorie", "Trong nhà"),
    ("Chihuahua", "Mexico", "Mexico", "Ấm / khô", "Trong nhà, tránh gió lạnh kéo dài", "18-29", "Toy", "1-3", "12-20", "Trung bình - cao/kg", "Trung bình", "Gà, bò, cá", "Hạt, wet, pate", "Gà, bò", "Mini jerky", "Hạt puppy toy breed", "Hạt adult small breed", "Hạt senior low calorie", "Trong nhà"),
    ("Shiba Inu", "Japan", "Nhật Bản", "Ôn đới / mát", "Nhà có sân, có vận động đều", "10-25", "Medium", "8-11", "12-15", "Trung bình - cao", "Cao", "Cá, gà, bò", "Hạt, wet", "Cá, gà", "Freeze-dried, dental", "Hạt puppy medium breed", "Hạt adult active", "Hạt senior joint care", "Nhà có sân"),
    ("Akita Inu", "Japan", "Nhật Bản", "Mát / lạnh", "Nhà rộng, không gian thoáng", "10-23", "Large", "30-50", "10-15", "Cao", "Cao", "Cá, gà, bò", "Hạt, wet", "Cá, gà", "Jerky, chew", "Hạt puppy large breed", "Hạt adult large active", "Hạt senior joint support", "Nhà rộng"),
    ("Siberian Husky", "Russia", "Siberia", "Lạnh / mát", "Sân rộng, không gian vận động", "-5 đến 25", "Medium/Large", "16-27", "12-14", "Cao", "Rất cao", "Cá, gà, cừu", "Hạt, wet", "Cá, gà", "Freeze-dried, chew", "Hạt puppy active", "Hạt adult working breed", "Hạt senior moderate calorie", "Nhà có sân rộng"),
    ("Alaskan Malamute", "United States", "Alaska", "Lạnh / mát", "Nhà rộng, sân thoáng", "-10 đến 20", "Large", "24-40", "10-14", "Cao", "Rất cao", "Bò, cá, gà", "Hạt, wet", "Bò, cá", "Jerky, dental", "Hạt puppy large breed", "Hạt adult active", "Hạt senior joint support", "Nhà rộng"),
    ("Corgi", "United Kingdom", "Wales", "Ôn đới / mát", "Nhà/căn hộ, có không gian đi bộ", "10-23", "Small/Medium", "10-15", "12-15", "Trung bình - cao", "Cao", "Gà, bò, cá", "Hạt, wet, pate", "Gà, bò", "Jerky, chew", "Hạt puppy medium breed", "Hạt adult active", "Hạt senior weight control", "Nhà/căn hộ"),
    ("Beagle", "United Kingdom", "Anh", "Ôn đới / mát", "Nhà có sân, đi bộ nhiều", "10-24", "Medium", "9-11", "10-15", "Cao", "Rất cao", "Gà, bò", "Hạt, pate, wet", "Gà, bò", "Jerky, dental", "Hạt puppy active", "Hạt adult active", "Hạt senior moderate calorie", "Nhà có sân"),
    ("Rottweiler", "Germany", "Đức", "Ôn đới / mát", "Nhà rộng, lịch tập luyện đều", "10-22", "Large", "35-60", "8-10", "Cao", "Rất cao", "Bò, gà, cừu", "Hạt, wet, pate", "Bò, gà", "Chew, jerky", "Hạt puppy large breed", "Hạt adult working breed", "Hạt senior joint care", "Nhà rộng"),
    ("Doberman", "Germany", "Đức", "Ôn đới / mát", "Nhà rộng, có không gian vận động", "10-23", "Large", "30-45", "10-12", "Cao", "Rất cao", "Gà, bò", "Hạt, pate", "Gà, bò", "Chew, jerky", "Hạt puppy large breed", "Hạt adult lean protein", "Hạt senior joint support", "Nhà rộng"),
    ("Border Collie", "United Kingdom", "Scotland", "Mát / ôn đới", "Nhà rộng, sân và công việc vận động", "10-21", "Medium/Large", "14-20", "10-14", "Rất cao", "Rất cao", "Gà, bò, cá", "Hạt, wet", "Gà, bò", "Freeze-dried, chew", "Hạt puppy active", "Hạt adult performance", "Hạt senior joint/brain support", "Nhà rộng"),
    ("Yorkshire Terrier", "United Kingdom", "Yorkshire", "Ôn đới / mát", "Trong nhà, ít di chuyển nhưng cần an toàn", "15-24", "Toy", "2-3", "11-15", "Trung bình", "Trung bình", "Gà, cá", "Hạt, wet, soft food", "Gà, cá", "Mini jerky", "Hạt puppy toy breed", "Hạt adult small breed", "Hạt senior low calorie", "Trong nhà"),
    ("Maltese", "Italy", "Địa Trung Hải", "Ấm / mát", "Trong nhà, cần giữ ấm khi lạnh", "18-27", "Toy", "2-4", "12-15", "Trung bình", "Trung bình", "Gà, cá", "Hạt, soft food", "Gà, cá", "Soft treat, dental", "Hạt puppy toy breed", "Hạt adult small breed", "Hạt senior delicate digest", "Trong nhà"),
    ("Shih Tzu", "China", "Tây Tạng / Trung Quốc", "Mát / ôn đới", "Trong nhà, thích điều kiện ấm và kín", "15-25", "Small", "4-7", "10-16", "Trung bình", "Thấp - trung bình", "Gà, cá", "Hạt, wet, soft", "Gà, cá", "Soft treat, dental", "Hạt puppy small breed", "Hạt adult small breed", "Hạt senior gentle digest", "Trong nhà"),
    ("Chow Chow", "China", "Bắc Trung Quốc", "Mát / lạnh", "Nhà thoáng, không ưa nắng nóng dài ngày", "10-22", "Medium/Large", "18-32", "9-15", "Trung bình", "Trung bình", "Cá, gà", "Hạt, wet", "Cá, gà", "Chew, dental", "Hạt puppy medium breed", "Hạt adult moderate active", "Hạt senior moderate calorie", "Nhà thoáng"),
    ("Samoyed", "Russia", "Siberia", "Lạnh / mát", "Có không gian rộng, không thích nhiệt cao", "-5 đến 22", "Large", "20-30", "12-14", "Cao", "Rất cao", "Cá, gà, cừu", "Hạt, wet", "Cá, gà", "Jerky, chew", "Hạt puppy active", "Hạt adult active", "Hạt senior joint support", "Nhà rộng"),
    ("Great Dane", "Germany", "Đức", "Ôn đới / mát", "Nhà rộng, sân thoáng", "10-24", "Giant", "45-90", "7-10", "Cao", "Trung bình - cao", "Gà, bò", "Hạt, wet, pate", "Gà, bò", "Chew, jerky", "Hạt puppy giant breed", "Hạt adult giant breed", "Hạt senior joint support", "Nhà rộng"),
    ("Saint Bernard", "Switzerland", "Alps", "Lạnh / mát", "Nhà rộng, không gian thoáng", "-10 đến 20", "Giant", "55-90", "8-10", "Trung bình", "Trung bình", "Bò, gà", "Hạt, wet", "Bò, gà", "Jerky, chew", "Hạt puppy giant breed", "Hạt adult giant adult", "Hạt senior joint support", "Nhà rộng"),
    ("Bichon Frise", "France/Italy", "Địa Trung Hải", "Mát / ôn đới", "Trong nhà, dễ sống ở căn hộ", "18-26", "Small", "3-6", "12-15", "Trung bình", "Trung bình", "Gà, cá", "Hạt, wet", "Gà, cá", "Soft treat, dental", "Hạt puppy small breed", "Hạt adult small breed", "Hạt senior delicate", "Trong nhà"),
    ("Dachshund", "Germany", "Đức", "Ôn đới / mát", "Nhà/căn hộ với không gian ngủ ấm", "15-24", "Small", "4-9", "12-16", "Trung bình", "Trung bình", "Gà, bò, cá", "Hạt, wet, pate", "Gà, bò", "Jerky, dental", "Hạt puppy small breed", "Hạt adult small active", "Hạt senior gentle digest", "Nhà/căn hộ"),
    ("Boxer", "Germany", "Đức", "Ôn đới / mát", "Nhà rộng, vận động đều", "10-23", "Large", "25-35", "8-10", "Cao", "Rất cao", "Bò, gà", "Hạt, wet", "Bò, gà", "Jerky, chew", "Hạt puppy large breed", "Hạt adult active", "Hạt senior joint support", "Nhà rộng"),
    ("Weimaraner", "Germany", "Đức", "Ôn đới / mát", "Nhà rộng, vận động mạnh", "10-23", "Large", "25-40", "10-13", "Cao", "Rất cao", "Gà, bò, cá", "Hạt, wet, pate", "Gà, cá", "Jerky, dental", "Hạt puppy active", "Hạt adult performance", "Hạt senior joint care", "Nhà rộng"),
    ("Australian Shepherd", "United States", "Úc", "Ôn đới / mát", "Nhà rộng, sân, công việc vận động", "10-22", "Medium/Large", "18-35", "12-15", "Cao", "Rất cao", "Gà, bò, cá", "Hạt, wet", "Gà, cá", "Jerky, chew", "Hạt puppy active", "Hạt adult active", "Hạt senior brain+joint support", "Nhà rộng"),
    ("Collie", "United Kingdom", "Scotland", "Mát / ôn đới", "Nhà rộng, sân", "10-23", "Medium/Large", "20-30", "10-14", "Trung bình - cao", "Cao", "Gà, bò, cá", "Hạt, wet", "Gà, cá", "Jerky, dental", "Hạt puppy medium breed", "Hạt adult active", "Hạt senior gentle digest", "Nhà rộng"),
    ("Basenji", "Congo", "Trung Phi", "Ấm / khô", "Nhà/căn hộ nếu có vận động ", "15-27", "Medium", "9-13", "10-14", "Trung bình - cao", "Cao", "Cá, gà, bò", "Hạt, wet", "Cá, gà", "Jerky, dental", "Hạt puppy medium breed", "Hạt adult active", "Hạt senior lean", "Nhà/căn hộ"),
    ("Cane Corso", "Italy", "Ý", "Ôn đới / mát", "Nhà rộng, sân và luyện tập", "10-22", "Large/Giant", "40-60", "9-12", "Cao", "Rất cao", "Bò, gà", "Hạt, wet, pate", "Bò, gà", "Jerky, chew", "Hạt puppy giant breed", "Hạt adult large breed", "Hạt senior joint support", "Nhà rộng"),
    ("Belgian Malinois", "Belgium", "Bỉ", "Ôn đới / mát", "Nhà rộng, công việc vận động", "10-22", "Medium/Large", "20-30", "10-14", "Rất cao", "Rất cao", "Gà, bò, cá", "Hạt, wet", "Gà, bò", "Jerky, chew", "Hạt puppy athletic", "Hạt adult performance", "Hạt senior joint support", "Nhà rộng"),
    ("Australian Cattle Dog", "Australia", "Úc", "Ôn đới", "Nhà rộng, sân, vận động cao", "10-22", "Medium", "15-25", "12-15", "Cao", "Rất cao", "Gà, bò, cừu", "Hạt, wet", "Gà, bò", "Jerky, chew", "Hạt puppy active", "Hạt adult working breed", "Hạt senior gentle digest", "Nhà rộng"),
    ("Basset Hound", "France", "Pháp", "Ôn đới / mát", "Nhà/căn hộ, đi bộ đều", "15-24", "Medium", "18-30", "10-12", "Trung bình", "Trung bình", "Gà, bò", "Hạt, wet", "Gà, bò", "Jerky, dental", "Hạt puppy small-medium", "Hạt adult moderate", "Hạt senior joint support", "Nhà/căn hộ"),
    ("Bloodhound", "United Kingdom", "Anh", "Ôn đới / mát", "Nhà rộng, vận động đều", "10-22", "Large", "35-50", "8-10", "Trung bình - cao", "Trung bình", "Gà, bò", "Hạt, wet", "Gà, bò", "Jerky, chew", "Hạt puppy active", "Hạt adult large breed", "Hạt senior joint support", "Nhà rộng"),
    ("Cavalier King Charles Spaniel", "United Kingdom", "Anh", "Ôn đới / mát", "Trong nhà, căn hộ hoặc nhà", "18-26", "Small/Medium", "5-8", "10-14", "Trung bình", "Trung bình", "Gà, cá", "Hạt, wet", "Gà, cá", "Soft treat, dental", "Hạt puppy small breed", "Hạt adult moderate", "Hạt senior heart-friendly", "Trong nhà"),
    ("Jack Russell Terrier", "United Kingdom", "Anh", "Ôn đới / mát", "Nhà có sân, vận động đều", "10-22", "Small", "5-8", "13-16", "Cao", "Rất cao", "Gà, cá", "Hạt, wet, pate", "Gà, cá", "Jerky, chew", "Hạt puppy small active", "Hạt adult active", "Hạt senior low-calorie", "Nhà có sân"),
    ("West Highland White Terrier", "United Kingdom", "Scotland", "Ôn đới / mát", "Nhà/căn hộ, cần vận động nhẹ", "15-24", "Small", "6-8", "12-16", "Trung bình", "Trung bình", "Gà, cá", "Hạt, wet", "Gà, cá", "Mini chew", "Hạt puppy small breed", "Hạt adult moderate", "Hạt senior low calorie", "Nhà/căn hộ"),
    ("Fox Terrier", "United Kingdom", "Anh", "Ôn đới / mát", "Nhà có sân, cần vận động", "15-25", "Small/Medium", "6-9", "12-15", "Cao", "Cao", "Gà, cá", "Hạt, wet", "Gà, cá", "Jerky, dental", "Hạt puppy active", "Hạt adult active", "Hạt senior moderate", "Nhà có sân"),
    ("Bullmastiff", "United Kingdom", "Anh", "Ôn đới / mát", "Nhà rộng, không gian riêng", "10-22", "Large", "40-60", "8-10", "Trung bình", "Trung bình", "Bò, gà", "Hạt, wet", "Bò, gà", "Jerky, chew", "Hạt puppy large breed", "Hạt adult large breed", "Hạt senior joint support", "Nhà rộng"),
    ("Mastiff", "United Kingdom", "Anh", "Ôn đới / mát", "Nhà rộng, không gian thoáng", "10-20", "Giant", "70-100", "7-10", "Trung bình", "Thấp - trung bình", "Bò, gà", "Hạt, wet", "Bò, gà", "Jerky, chew", "Hạt puppy giant breed", "Hạt adult giant breed", "Hạt senior joint support", "Nhà rộng"),
    ("Newfoundland", "Canada", "Newfoundland", "Lạnh / mát", "Nhà rộng, gần nước nếu có điều kiện", "5-18", "Giant", "45-70", "8-10", "Trung bình - cao", "Trung bình", "Cá, gà, bò", "Hạt, wet", "Cá, gà", "Jerky, chew", "Hạt puppy giant breed", "Hạt adult giant breed", "Hạt senior joint support", "Nhà rộng"),
    ("Bernese Mountain Dog", "Switzerland", "Thụy Sĩ", "Mát / ôn đới", "Nhà rộng, sân và không gian yên tĩnh", "10-20", "Large", "30-50", "7-10", "Trung bình - cao", "Cao", "Gà, bò", "Hạt, wet", "Gà, bò", "Jerky, chew", "Hạt puppy large breed", "Hạt adult large breed", "Hạt senior joint support", "Nhà rộng"),
    ("Cocker Spaniel", "United Kingdom", "Anh", "Ôn đới / mát", "Nhà/căn hộ, đi bộ đều", "15-24", "Medium", "7-14", "10-14", "Trung bình", "Trung bình", "Gà, cá, bò", "Hạt, wet", "Gà, cá", "Jerky, dental", "Hạt puppy medium breed", "Hạt adult regular protein", "Hạt senior manage weight", "Nhà/căn hộ"),
    ("Irish Setter", "Ireland", "Ireland", "Ôn đới / mát", "Nhà có sân, vận động cao", "10-22", "Medium/Large", "20-30", "12-15", "Cao", "Rất cao", "Gà, bò, cá", "Hạt, wet", "Gà, bò", "Jerky, chew", "Hạt puppy active", "Hạt adult performance", "Hạt senior joint support", "Nhà có sân"),
    ("Basset Hound", "France", "Pháp", "Ôn đới / mát", "Nhà/căn hộ, đi bộ đều", "15-24", "Medium", "18-30", "10-12", "Trung bình", "Trung bình", "Gà, bò", "Hạt, wet", "Gà, bò", "Jerky, dental", "Hạt puppy small-medium", "Hạt adult moderate", "Hạt senior joint support", "Nhà/căn hộ"),
    ("Miniature Poodle", "France", "Tây Âu", "Ôn đới / mát", "Nhà/căn hộ, cần vận động", "15-25", "Small", "4-7", "12-15", "Trung bình - cao", "Cao", "Gà, cá, vịt", "Hạt, wet", "Gà, cá", "Jerky, dental", "Hạt puppy mini breed", "Hạt adult moderate", "Hạt senior coat care", "Nhà/căn hộ"),
    ("Standard Poodle", "France", "Tây Âu", "Ôn đới / mát", "Nhà có sân hoặc căn hộ có vận động", "15-25", "Medium/Large", "20-30", "12-15", "Cao", "Rất cao", "Gà, cá, vịt", "Hạt, wet", "Gà, cá", "Jerky, chew", "Hạt puppy standard", "Hạt adult active", "Hạt senior coat care", "Nhà có sân"),
    ("Havanese", "Cuba", "Cuba", "Ấm / mát", "Trong nhà, căn hộ phù hợp", "18-27", "Small", "3-6", "14-16", "Trung bình", "Trung bình", "Gà, cá", "Hạt, wet", "Gà, cá", "Soft treat, dental", "Hạt puppy small breed", "Hạt adult small breed", "Hạt senior gentle digest", "Trong nhà"),
    ("Bolognese", "Italy", "Ý", "Ấm / mát", "Trong nhà, dễ sống ở căn hộ", "18-26", "Small", "2-4", "12-15", "Thấp - trung bình", "Thấp - trung bình", "Gà, cá", "Hạt, wet", "Gà, cá", "Soft treat, dental", "Hạt puppy small breed", "Hạt adult small breed", "Hạt senior low calorie", "Trong nhà"),
    ("Irish Wolfhound", "Ireland", "Ireland", "Ôn đới / mát", "Nhà rộng, không gian thoáng", "10-20", "Giant", "48-90", "6-8", "Trung bình", "Trung bình", "Gà, bò", "Hạt, wet", "Gà, bò", "Jerky, chew", "Hạt puppy giant breed", "Hạt adult giant breed", "Hạt senior joint support", "Nhà rộng"),
    ("Shar Pei", "China", "Trung Quốc", "Ôn đới / mát", "Nhà thoáng, không gian riêng", "15-25", "Medium/Large", "18-30", "8-12", "Trung bình", "Trung bình", "Gà, bò", "Hạt, wet", "Gà, bò", "Jerky, dental", "Hạt puppy moderate", "Hạt adult moderate", "Hạt senior joint support", "Nhà thoáng"),
    ("Chinese Crested", "China", "Trung Quốc", "Ấm / mát", "Trong nhà, không gian yên tĩnh", "18-28", "Small", "4-6", "13-18", "Trung bình", "Trung bình", "Gà, cá", "Hạt, wet", "Gà, cá", "Soft treat, dental", "Hạt puppy toy breed", "Hạt adult small breed", "Hạt senior low calorie", "Trong nhà"),
    ("Dogo Argentino", "Argentina", "Argentina", "Ôn đới / mát", "Nhà rộng, cần huấn luyện", "10-22", "Large", "35-45", "9-12", "Cao", "Rất cao", "Bò, gà", "Hạt, wet", "Bò, gà", "Jerky, chew", "Hạt puppy active", "Hạt adult performance", "Hạt senior joint support", "Nhà rộng"),
    ("Staffordshire Bull Terrier", "United Kingdom", "Anh", "Ôn đới / mát", "Nhà/căn hộ nếu tập luyện đều", "15-25", "Medium", "11-17", "12-15", "Cao", "Cao", "Bò, gà", "Hạt, wet", "Bò, gà", "Jerky, chew", "Hạt puppy medium breed", "Hạt adult active", "Hạt senior moderate", "Nhà/căn hộ"),
    ("Dalmatian", "Croatia", "Croatia", "Ôn đới / mát", "Nhà rộng, vận động đều", "10-23", "Medium/Large", "20-35", "10-13", "Trung bình - cao", "Cao", "Gà, bò, cá", "Hạt, wet", "Gà, bò", "Jerky, chew", "Hạt puppy active", "Hạt adult active", "Hạt senior joint support", "Nhà rộng"),
    ("Pekingese", "China", "Bắc Trung Quốc", "Mát / ôn đới", "Trong nhà, dễ sống ở căn hộ", "15-25", "Small", "4-7", "12-15", "Thấp - trung bình", "Thấp - trung bình", "Gà, cá", "Hạt, wet", "Gà, cá", "Soft treat, dental", "Hạt puppy toy breed", "Hạt adult small breed", "Hạt senior low calorie", "Trong nhà"),
    ("Tibetan Mastiff", "Tibet", "Tây Tạng", "Mát / lạnh", "Nhà rộng, khu vực thoáng", "-5 đến 20", "Giant", "45-75", "10-14", "Trung bình", "Trung bình", "Bò, gà", "Hạt, wet", "Bò, gà", "Jerky, chew", "Hạt puppy giant breed", "Hạt adult giant breed", "Hạt senior joint support", "Nhà rộng"),
    ("Korean Jindo", "South Korea", "Hàn Quốc", "Ôn đới / mát", "Nhà rộng, có sân", "10-22", "Medium/Large", "18-30", "12-15", "Cao", "Cao", "Gà, bò, cá", "Hạt, wet", "Gà, cá", "Jerky, chew", "Hạt puppy active", "Hạt adult active", "Hạt senior moderate", "Nhà rộng"),
    ("Whippet", "United Kingdom", "Anh", "Ôn đới / mát", "Nhà/căn hộ nếu vận động, thích chạy", "15-24", "Medium", "10-20", "12-15", "Cao", "Rất cao", "Gà, cá", "Hạt, wet", "Gà, cá", "Jerky, chew", "Hạt puppy active", "Hạt adult active", "Hạt senior lean", "Nhà/căn hộ"),
    ("Greyhound", "United Kingdom", "Anh", "Ôn đới / mát", "Nhà/căn hộ, cần vận động đều", "15-25", "Large", "26-35", "10-13", "Trung bình - cao", "Cao", "Gà, cá", "Hạt, wet", "Gà, cá", "Jerky, chew", "Hạt puppy large breed", "Hạt adult lean", "Hạt senior joint support", "Nhà/căn hộ"),
    ("Afghan Hound", "Afghanistan", "Afghanistan", "Khô / mát", "Nhà rộng, khí hậu thoáng", "10-25", "Large", "20-30", "12-15", "Trung bình - cao", "Cao", "Gà, cá", "Hạt, wet", "Gà, cá", "Jerky, chew", "Hạt puppy active", "Hạt adult active", "Hạt senior coat care", "Nhà rộng"),
    ("English Setter", "United Kingdom", "Anh", "Ôn đới / mát", "Nhà có sân, không gian đi bộ", "12-23", "Medium/Large", "20-30", "10-12", "Cao", "Rất cao", "Gà, cá", "Hạt, wet", "Gà, cá", "Jerky, chew", "Hạt puppy active", "Hạt adult performance", "Hạt senior moderate", "Nhà có sân"),
    ("Airedale Terrier", "United Kingdom", "Anh", "Ôn đới / mát", "Nhà rộng, vận động cao", "10-22", "Medium/Large", "20-30", "10-12", "Cao", "Rất cao", "Gà, bò", "Hạt, wet", "Gà, bò", "Jerky, chew", "Hạt puppy active", "Hạt adult active", "Hạt senior joint support", "Nhà rộng"),
    ("Shetland Sheepdog", "United Kingdom", "Scotland", "Ôn đới / mát", "Nhà/căn hộ nếu vận động đều", "12-22", "Small/Medium", "10-15", "12-15", "Cao", "Rất cao", "Gà, cá", "Hạt, wet", "Gà, cá", "Jerky, chew", "Hạt puppy active", "Hạt adult active", "Hạt senior joint support", "Nhà/căn hộ"),
    ("Papillon", "Belgium / France", "Tây Âu", "Ôn đới / mát", "Trong nhà, căn hộ phù hợp", "18-26", "Toy", "2-5", "12-16", "Trung bình", "Trung bình", "Gà, cá", "Hạt, wet", "Gà, cá", "Mini chew", "Hạt puppy toy breed", "Hạt adult small breed", "Hạt senior gentle digest", "Trong nhà"),
    ("Miniature Schnauzer", "Germany", "Đức", "Ôn đới / mát", "Nhà, có thể căn hộ nếu vận động đủ", "15-25", "Small", "5-8", "12-15", "Trung bình", "Trung bình", "Gà, cá", "Hạt, wet, pate", "Gà, cá", "Jerky, dental", "Hạt puppy small breed", "Hạt adult small active", "Hạt senior kidney-safe", "Nhà/căn hộ"),
]

CATS = [
    ("British Shorthair", "United Kingdom", "Anh", "Mát / ôn đới", "Trong nhà, dễ sống ở căn hộ", "15-25", "Medium/Large", "4-8", "12-17", "Trung bình", "Trung bình", "Gà, cá, bò", "Hạt, wet, pate", "Gà, cá", "Bánh thưởng, dental", "Hạt kitten growth", "Hạt adult steady", "Hạt senior moderate", "Trong nhà"),
    ("Scottish Fold", "United Kingdom", "Scotland", "Mát / ôn đới", "Trong nhà, môi trường ấm và yên tĩnh", "15-24", "Medium", "3-7", "12-15", "Trung bình", "Trung bình", "Gà, cá", "Hạt, wet", "Gà, cá", "Soft treat", "Hạt kitten growth", "Hạt adult gentle", "Hạt senior gentle digest", "Trong nhà"),
    ("Persian", "Iran", "Ba Tư", "Mát / ôn đới", "Trong nhà, yên tĩnh, sạch sẽ", "15-25", "Medium/Large", "3-7", "12-18", "Thấp - trung bình", "Thấp - trung bình", "Gà, cá", "Hạt, wet, pate", "Gà, cá", "Soft treat, dental", "Hạt kitten growth", "Hạt adult low activity", "Hạt senior gentle digestion", "Trong nhà"),
    ("Maine Coon", "United States", "Maine", "Mát / lạnh", "Nhà rộng, thoáng", "10-22", "Large", "5-9", "10-15", "Trung bình - cao", "Trung bình - cao", "Gà, cá, bò", "Hạt, wet", "Gà, cá", "Jerky, dental", "Hạt kitten growth", "Hạt adult active", "Hạt senior lean support", "Nhà rộng"),
    ("Ragdoll", "United States", "California", "Ôn đới / mát", "Trong nhà, thoải mái", "15-24", "Large", "4-9", "12-18", "Trung bình", "Trung bình", "Gà, cá", "Hạt, wet, pate", "Gà, cá", "Soft treat, dental", "Hạt kitten growth", "Hạt adult gentle", "Hạt senior adult support", "Trong nhà"),
    ("Siamese", "Thailand", "Thái Lan", "Ấm / mát", "Trong nhà, gần chủ, cần tương tác", "18-28", "Medium", "3-6", "10-15", "Cao", "Rất cao", "Cá, gà", "Hạt, wet, pate", "Cá, gà", "Freeze-dried treat", "Hạt kitten high protein", "Hạt adult active", "Hạt senior moderate", "Trong nhà"),
    ("Bengal", "United States", "Mỹ", "Ấm / ôn đới", "Trong nhà, cần đồ chơi và vận động", "15-26", "Medium/Large", "4-8", "10-15", "Cao - rất cao", "Rất cao", "Thịt, cá, gà", "Hạt, wet, raw-style*", "Cá, gà", "Freeze-dried, jerky", "Hạt kitten active", "Hạt adult high activity", "Hạt senior lean", "Trong nhà"),
    ("Sphynx", "Canada", "Canada", "Ấm / mát", "Trong nhà, giữ ấm và vệ sinh sạch", "18-28", "Medium", "3-6", "10-14", "Cao", "Cao", "Gà, cá", "Hạt, wet", "Gà, cá", "Soft treat, dental", "Hạt kitten growth", "Hạt adult rich protein", "Hạt senior gentle digest", "Trong nhà"),
    ("Russian Blue", "Russia", "Nga", "Mát / lạnh", "Trong nhà, sạch và yên tĩnh", "15-24", "Medium", "3-6", "10-15", "Trung bình", "Trung bình", "Cá, gà", "Hạt, wet", "Cá, gà", "Dental treat", "Hạt kitten growth", "Hạt adult gentle", "Hạt senior moderate", "Trong nhà"),
    ("Norwegian Forest Cat", "Norway", "Na Uy", "Lạnh / mát", "Nhà thoáng, không gian rộng", "10-22", "Large", "4-8", "12-16", "Trung bình - cao", "Trung bình - cao", "Cá, gà", "Hạt, wet", "Cá, gà", "Jerky, dental", "Hạt kitten growth", "Hạt adult active", "Hạt senior moderate", "Nhà thoáng"),
    ("Birman", "Myanmar / France", "Myanmar / Pháp", "Ấm / mát", "Trong nhà, yên bình", "15-24", "Medium/Large", "3-7", "10-15", "Trung bình", "Trung bình", "Gà, cá", "Hạt, wet", "Gà, cá", "Soft treat, dental", "Hạt kitten growth", "Hạt adult gentle", "Hạt senior gentle digest", "Trong nhà"),
    ("Abyssinian", "Ethiopia", "Đông Bắc Phi", "Ấm / ôn đới", "Trong nhà, cần tương tác và đồ chơi", "18-28", "Medium", "3-5", "9-15", "Cao", "Rất cao", "Cá, gà", "Hạt, wet", "Cá, gà", "Freeze-dried treat", "Hạt kitten active", "Hạt adult active", "Hạt senior moderate", "Trong nhà"),
    ("American Shorthair", "United States", "Mỹ", "Ôn đới / mát", "Trong nhà, dễ thích nghi nhiều môi trường", "15-25", "Medium", "3-6", "12-15", "Trung bình", "Trung bình", "Gà, cá, bò", "Hạt, wet, pate", "Gà, cá", "Dental treat", "Hạt kitten growth", "Hạt adult balanced", "Hạt senior moderate", "Trong nhà"),
    ("Exotic Shorthair", "United States", "Mỹ", "Mát / ôn đới", "Trong nhà, yên tĩnh", "15-25", "Medium", "3-6", "10-15", "Trung bình", "Thấp - trung bình", "Gà, cá", "Hạt, wet", "Gà, cá", "Soft treat", "Hạt kitten growth", "Hạt adult gentle", "Hạt senior gentle digest", "Trong nhà"),
    ("Turkish Angora", "Turkey", "Ankara", "Ôn đới / mát", "Trong nhà, cần vận động nhẹ", "15-25", "Medium", "3-5", "12-18", "Trung bình - cao", "Cao", "Cá, gà", "Hạt, wet", "Cá, gà", "Soft treat, dental", "Hạt kitten growth", "Hạt adult active", "Hạt senior moderate", "Trong nhà"),
    ("Turkish Van", "Turkey", "Vùng hồ Van", "Ôn đới / mát", "Nhà thoáng, không gian đi lại", "15-25", "Medium", "3-7", "12-17", "Trung bình - cao", "Cao", "Cá, gà", "Hạt, wet", "Cá, gà", "Freeze-dried treat", "Hạt kitten growth", "Hạt adult active", "Hạt senior moderate", "Nhà thoáng"),
    ("Oriental Shorthair", "United Kingdom", "Anh", "Ấm / ôn đới", "Trong nhà, cần tương tác", "15-25", "Medium", "3-5", "10-15", "Cao", "Rất cao", "Cá, gà", "Hạt, wet", "Cá, gà", "Freeze-dried treat", "Hạt kitten high protein", "Hạt adult active", "Hạt senior moderate", "Trong nhà"),
    ("Burmese", "Thailand / Myanmar", "Đông Nam Á", "Ấm / mát", "Trong nhà, gần chủ", "18-28", "Medium", "3-6", "10-16", "Cao", "Cao", "Gà, cá, bò", "Hạt, wet", "Gà, cá", "Soft treat", "Hạt kitten growth", "Hạt adult active", "Hạt senior moderate", "Trong nhà"),
    ("Devon Rex", "United Kingdom", "Devon", "Mát / ôn đới", "Trong nhà, giữ ấm", "18-26", "Small/Medium", "2-4", "10-15", "Cao", "Cao", "Gà, cá", "Hạt, wet", "Gà, cá", "Soft treat, dental", "Hạt kitten growth", "Hạt adult active", "Hạt senior gentle digest", "Trong nhà"),
    ("Cornish Rex", "United Kingdom", "Cornwall", "Mát / ôn đới", "Trong nhà, giữ ấm", "18-26", "Small/Medium", "2-5", "10-15", "Cao", "Cao", "Gà, cá", "Hạt, wet", "Gà, cá", "Soft treat, dental", "Hạt kitten growth", "Hạt adult active", "Hạt senior gentle digest", "Trong nhà"),
    ("Balinese", "United States", "Mỹ", "Ấm / mát", "Trong nhà, gần chủ", "18-28", "Medium", "3-5", "10-15", "Cao", "Cao", "Cá, gà", "Hạt, wet", "Cá, gà", "Freeze-dried treat", "Hạt kitten growth", "Hạt adult active", "Hạt senior moderate", "Trong nhà"),
    ("Ocicat", "United States", "Mỹ", "Ấm / ôn đới", "Trong nhà, cần đồ chơi và tương tác", "18-28", "Medium", "3-6", "12-15", "Cao", "Rất cao", "Cá, gà, bò", "Hạt, wet", "Cá, gà", "Jerky, chew", "Hạt kitten active", "Hạt adult active", "Hạt senior moderate", "Trong nhà"),
    ("Himalayan", "United States", "Mỹ", "Mát / ôn đới", "Trong nhà, yên tĩnh", "15-25", "Medium/Large", "3-7", "12-16", "Trung bình", "Thấp - trung bình", "Gà, cá", "Hạt, wet", "Gà, cá", "Soft treat", "Hạt kitten growth", "Hạt adult gentle", "Hạt senior gentle digest", "Trong nhà"),
    ("Selkirk Rex", "United States", "Mỹ", "Mát / ôn đới", "Trong nhà, môi trường ổn định", "15-25", "Medium", "3-7", "12-15", "Trung bình", "Trung bình", "Gà, cá", "Hạt, wet", "Gà, cá", "Soft treat", "Hạt kitten growth", "Hạt adult gentle", "Hạt senior moderate", "Trong nhà"),
    ("Manx", "United Kingdom", "Anh", "Ôn đới / mát", "Trong nhà, không gian dễ di chuyển", "15-25", "Medium", "3-6", "12-14", "Trung bình", "Trung bình", "Gà, cá", "Hạt, wet", "Gà, cá", "Soft treat", "Hạt kitten growth", "Hạt adult balanced", "Hạt senior moderate", "Trong nhà"),
    ("Egyptian Mau", "Egypt", "Ai Cập", "Ấm / khô", "Trong nhà, cần vận động và đồ chơi", "18-28", "Medium", "3-6", "12-15", "Cao", "Cao", "Cá, gà, bò", "Hạt, wet", "Cá, gà", "Jerky, dental", "Hạt kitten active", "Hạt adult active", "Hạt senior moderate", "Trong nhà"),
    ("LaPerm", "United States", "Mỹ", "Ấm / mát", "Trong nhà, dễ sống nếu tương tác", "18-28", "Medium", "3-6", "12-15", "Trung bình - cao", "Cao", "Gà, cá", "Hạt, wet", "Gà, cá", "Soft treat, dental", "Hạt kitten active", "Hạt adult active", "Hạt senior moderate", "Trong nhà"),
    ("Bombay", "United States", "Mỹ", "Ấm / mát", "Trong nhà, gần chủ", "18-25", "Medium", "3-6", "12-16", "Trung bình", "Trung bình", "Gà, cá", "Hạt, wet", "Gà, cá", "Soft treat", "Hạt kitten growth", "Hạt adult moderate", "Hạt senior moderate", "Trong nhà"),
    ("Chartreux", "France", "Pháp", "Ôn đới / mát", "Trong nhà, yên tĩnh", "15-25", "Medium/Large", "3-7", "12-15", "Trung bình", "Trung bình", "Gà, cá", "Hạt, wet", "Gà, cá", "Soft treat", "Hạt kitten growth", "Hạt adult balanced", "Hạt senior moderate", "Trong nhà"),
    ("Cymric", "United Kingdom", "Anh", "Ôn đới / mát", "Trong nhà, không gian thoải mái", "15-25", "Medium", "3-6", "12-14", "Trung bình", "Trung bình", "Gà, cá", "Hạt, wet", "Gà, cá", "Soft treat", "Hạt kitten growth", "Hạt adult gentle", "Hạt senior moderate", "Trong nhà"),
    ("Korat", "Thailand", "Thái Lan", "Ấm / mát", "Trong nhà, cần tương tác", "15-25", "Medium", "3-5", "10-15", "Trung bình - cao", "Cao", "Cá, gà", "Hạt, wet", "Cá, gà", "Freeze-dried treat", "Hạt kitten growth", "Hạt adult active", "Hạt senior moderate", "Trong nhà"),
    ("Nebelung", "United States", "Mỹ", "Ôn đới / mát", "Trong nhà, yên tĩnh", "15-25", "Medium", "3-6", "12-15", "Trung bình", "Trung bình", "Cá, gà", "Hạt, wet", "Cá, gà", "Soft treat", "Hạt kitten growth", "Hạt adult moderate", "Hạt senior moderate", "Trong nhà"),
    ("Pixiebob", "United States", "Mỹ", "Ấm / ôn đới", "Trong nhà, cần tương tác", "15-25", "Medium/Large", "3-8", "12-16", "Cao", "Cao", "Gà, cá", "Hạt, wet", "Gà, cá", "Jerky, chew", "Hạt kitten active", "Hạt adult active", "Hạt senior moderate", "Trong nhà"),
    ("Snowshoe", "United States", "Mỹ", "Ôn đới / mát", "Trong nhà, yên tĩnh", "15-25", "Medium", "3-6", "12-15", "Trung bình", "Trung bình", "Gà, cá", "Hạt, wet", "Gà, cá", "Soft treat", "Hạt kitten growth", "Hạt adult balanced", "Hạt senior moderate", "Trong nhà"),
    ("Tonkinese", "United States", "Mỹ", "Ấm / mát", "Trong nhà, cần tương tác", "18-28", "Medium", "3-6", "10-15", "Cao", "Cao", "Gà, cá", "Hạt, wet", "Gà, cá", "Freeze-dried treat", "Hạt kitten active", "Hạt adult active", "Hạt senior moderate", "Trong nhà"),
    ("Javanese", "United States", "Mỹ", "Ấm / mát", "Trong nhà, gần chủ", "18-28", "Medium", "3-6", "10-15", "Cao", "Cao", "Cá, gà", "Hạt, wet", "Cá, gà", "Freeze-dried treat", "Hạt kitten active", "Hạt adult active", "Hạt senior moderate", "Trong nhà"),
    ("Havana Brown", "United Kingdom", "Anh", "Ấm / mát", "Trong nhà, yên tĩnh", "15-25", "Medium", "3-6", "10-15", "Trung bình", "Trung bình", "Gà, cá", "Hạt, wet", "Gà, cá", "Soft treat", "Hạt kitten growth", "Hạt adult balanced", "Hạt senior moderate", "Trong nhà"),
    ("American Curl", "United States", "Mỹ", "Ôn đới / mát", "Trong nhà, dễ sống ở căn hộ", "15-25", "Medium", "3-6", "12-16", "Trung bình", "Trung bình", "Gà, cá", "Hạt, wet", "Gà, cá", "Soft treat", "Hạt kitten growth", "Hạt adult balanced", "Hạt senior gentle digest", "Trong nhà"),
]

extra_dogs = [
    ("Dandie Dinmont Terrier", "United Kingdom", "Scotland", "Oon doi / mat", "Nha co san, van dong nhe", "15-24", "Small", "5-8", "12-15", "Trung binh", "Trung binh", "Ga, ca", "Hat, wet", "Ga, ca", "Soft treat, dental", "Hat puppy small breed", "Hat adult small breed", "Hat senior moderate", "Nha co san"),
    ("Lagotto Romagnolo", "Italy", "Emilia-Romagna", "Oon doi / mat", "Nha hoac can ho, can van dong", "15-24", "Medium", "10-15", "14-16", "Trung binh", "Cao", "Ca, ga, bo", "Hat, wet", "Ca, ga", "Jerky, dental", "Hat puppy active", "Hat adult active", "Hat senior moderate", "Nha/can ho"),
    ("Keeshond", "Netherlands", "Holland", "Oon doi / mat", "Nha co san, vang lai", "10-22", "Medium", "15-20", "12-15", "Trung binh - cao", "Cao", "Ga, ca", "Hat, wet", "Ga, ca", "Jerky, chew", "Hat puppy active", "Hat adult active", "Hat senior gentle digest", "Nha co san"),
    ("Norfolk Terrier", "United Kingdom", "England", "Oon doi / mat", "Nha co san, van dong nhe", "15-25", "Small", "5-7", "12-15", "Trung binh", "Trung binh", "Ga, ca", "Hat, wet", "Ga, ca", "Mini chew", "Hat puppy small breed", "Hat adult small breed", "Hat senior low calorie", "Nha co san"),
    ("Affenpinscher", "Germany", "Germany", "Oon doi / mat", "Trong nha, can tuong tac", "15-25", "Small", "3-5", "12-15", "Trung binh", "Trung binh", "Ga, ca", "Hat, wet", "Ga, ca", "Mini chew", "Hat puppy toy breed", "Hat adult small breed", "Hat senior low calorie", "Trong nha"),
    ("Hokkaido", "Japan", "Hokkaido", "Mat / lanh", "Nha rong, san thoang", "-5 den 20", "Medium/Large", "18-30", "10-15", "Cao", "Cao", "Ga, ca", "Hat, wet", "Ga, ca", "Jerky, chew", "Hat puppy active", "Hat adult working breed", "Hat senior moderate", "Nha rong"),
    ("Japanese Spitz", "Japan", "Nhat Ban", "Oon doi / mat", "Nha co san, trong nha", "10-22", "Small/Medium", "5-10", "10-16", "Trung binh", "Trung binh", "Ga, ca", "Hat, wet", "Ga, ca", "Soft treat, dental", "Hat puppy small breed", "Hat adult small breed", "Hat senior low calorie", "Nha/can ho"),
    ("Shikoku", "Japan", "Shikoku", "Oon doi / mat", "Nha rong, van dong cao", "10-22", "Medium", "15-25", "10-15", "Cao", "Rất cao", "Ga, ca, bo", "Hat, wet", "Ga, ca", "Jerky, chew", "Hat puppy active", "Hat adult active", "Hat senior moderate", "Nha rong"),
    ("Kai Ken", "Japan", "Kai", "Oon doi / mat", "Nha rong, can van dong", "8-20", "Medium", "10-15", "12-15", "Cao", "Rất cao", "Ga, ca", "Hat, wet", "Ga, ca", "Jerky, chew", "Hat puppy active", "Hat adult active", "Hat senior joint support", "Nha rong"),
    ("Tibetan Terrier", "Tibet", "Tay Tang", "Mat / lanh", "Nha thoang, trong nha", "-5 den 18", "Medium", "10-18", "12-15", "Trung binh", "Trung binh", "Ga, ca", "Hat, wet", "Ga, ca", "Soft treat, dental", "Hat puppy medium breed", "Hat adult moderate", "Hat senior gentle digest", "Nha thoang"),
    ("Lhasa Apso", "Tibet", "Tay Tang", "Mat / lanh", "Trong nha, yên tinh", "10-20", "Small", "5-8", "12-18", "Thap - trung binh", "Thap - trung binh", "Ga, ca", "Hat, wet", "Ga, ca", "Soft treat, dental", "Hat puppy small breed", "Hat adult small breed", "Hat senior gentle digest", "Trong nha"),
    ("Puli", "Hungary", "Hungary", "Oon doi / mat", "Nha co san, can van dong", "10-22", "Medium", "10-15", "12-16", "Cao", "Cao", "Ga, ca", "Hat, wet", "Ga, ca", "Jerky, dental", "Hat puppy active", "Hat adult active", "Hat senior moderate", "Nha co san"),
    ("Komondor", "Hungary", "Hungary", "Oon doi / mat", "Nha rong, san thoang", "10-22", "Large", "30-50", "10-12", "Trung binh", "Trung binh", "Bo, ga", "Hat, wet", "Bo, ga", "Jerky, chew", "Hat puppy large breed", "Hat adult large breed", "Hat senior joint support", "Nha rong"),
    ("Briard", "France", "Phap", "Oon doi / mat", "Nha rong, van dong cao", "10-22", "Large", "30-40", "10-12", "Cao", "Rất cao", "Ga, bo", "Hat, wet", "Ga, bo", "Jerky, chew", "Hat puppy active", "Hat adult active", "Hat senior joint support", "Nha rong"),
    ("Clumber Spaniel", "United Kingdom", "England", "Oon doi / mat", "Nha thoang, di bo deu", "10-22", "Medium/Large", "20-30", "10-12", "Trung binh", "Trung binh", "Ga, bo", "Hat, wet", "Ga, bo", "Jerky, dental", "Hat puppy medium breed", "Hat adult moderate", "Hat senior weight control", "Nha thoang"),
    ("Field Spaniel", "United Kingdom", "England", "Oon doi / mat", "Nha co san, di bo deu", "10-22", "Medium", "15-25", "10-12", "Trung binh", "Trung binh", "Ga, bo", "Hat, wet", "Ga, bo", "Jerky, dental", "Hat puppy medium breed", "Hat adult active", "Hat senior weight control", "Nha co san"),
    ("English Springer Spaniel", "United Kingdom", "England", "Oon doi / mat", "Nha co san, van dong cao", "10-22", "Medium", "18-25", "10-13", "Cao", "Cao", "Ga, bo", "Hat, wet", "Ga, bo", "Jerky, chew", "Hat puppy active", "Hat adult active", "Hat senior moderate", "Nha co san"),
    ("Welsh Springer Spaniel", "United Kingdom", "Wales", "Oon doi / mat", "Nha co san, cuoc song van dong", "10-22", "Medium", "15-25", "12-14", "Cao", "Cao", "Ga, ca", "Hat, wet", "Ga, ca", "Jerky, dental", "Hat puppy active", "Hat adult active", "Hat senior moderate", "Nha co san"),
    ("Cairn Terrier", "United Kingdom", "Scotland", "Oon doi / mat", "Nha co san, van dong nhe", "15-24", "Small", "6-8", "12-15", "Trung binh", "Trung binh", "Ga, ca", "Hat, wet", "Ga, ca", "Mini chew", "Hat puppy small breed", "Hat adult small breed", "Hat senior low calorie", "Nha co san"),
    ("Scottish Terrier", "United Kingdom", "Scotland", "Oon doi / mat", "Nha co san, can kem ho tro", "15-24", "Small", "7-10", "11-13", "Trung binh", "Trung binh", "Ga, ca", "Hat, wet", "Ga, ca", "Mini chew", "Hat puppy small breed", "Hat adult moderate", "Hat senior low calorie", "Nha co san"),
    ("Sealyham Terrier", "United Kingdom", "Wales", "Oon doi / mat", "Nha co san, can buoi chac", "15-24", "Small", "8-10", "12-14", "Trung binh", "Trung binh", "Ga, ca", "Hat, wet", "Ga, ca", "Soft treat", "Hat puppy small breed", "Hat adult small breed", "Hat senior low calorie", "Nha co san"),
    ("Tenterfield Terrier", "Australia", "Australia", "Oon doi / mat", "Nha co san, di bo deu", "15-22", "Small", "5-8", "12-14", "Trung binh", "Cao", "Ga, ca", "Hat, wet", "Ga, ca", "Jerky, dental", "Hat puppy active", "Hat adult active", "Hat senior moderate", "Nha co san"),
    ("Silky Terrier", "Australia", "Australia", "Oon doi / mat", "Trong nha, can tuong tac", "18-27", "Small", "3-5", "12-15", "Trung binh", "Trung binh", "Ga, ca", "Hat, soft", "Ga, ca", "Soft treat, dental", "Hat puppy toy breed", "Hat adult small breed", "Hat senior low calorie", "Trong nha"),
    ("Parson Russell Terrier", "United Kingdom", "England", "Oon doi / mat", "Nha co san, van dong cao", "15-25", "Small", "5-8", "13-15", "Cao", "Rất cao", "Ga, ca", "Hat, wet", "Ga, ca", "Jerky, dental", "Hat puppy active", "Hat adult active", "Hat senior moderate", "Nha co san"),
    ("Rat Terrier", "United States", "Mỹ", "Oon doi / mat", "Nha co san, van dong cao", "15-25", "Small/Medium", "5-12", "12-18", "Cao", "Cao", "Ga, ca", "Hat, wet", "Ga, ca", "Jerky, chew", "Hat puppy active", "Hat adult active", "Hat senior moderate", "Nha co san"),
    ("Tosa Inu", "Japan", "Tosa", "Oon doi / mat", "Nha rong, huan luyen luong", "10-22", "Large", "35-60", "8-12", "Trung binh", "Cao", "Bo, ga", "Hat, wet", "Bo, ga", "Jerky, chew", "Hat puppy large breed", "Hat adult large breed", "Hat senior joint support", "Nha rong"),
    ("Japanese Terrier", "Japan", "Nhat Ban", "Oon doi / mat", "Trong nha, de song", "18-27", "Small", "4-7", "12-14", "Trung binh", "Trung binh", "Ga, ca", "Hat, wet", "Ga, ca", "Soft treat, dental", "Hat puppy small breed", "Hat adult small breed", "Hat senior low calorie", "Trong nha"),
    ("Karelian Bear Dog", "Finland", "Finland", "Lanh / mat", "Nha rong, van dong cao", "-10 den 18", "Medium/Large", "20-30", "10-12", "Cao", "Rất cao", "Ga, ca", "Hat, wet", "Ga, ca", "Jerky, chew", "Hat puppy active", "Hat adult working breed", "Hat senior moderate", "Nha rong"),
    ("Finnish Spitz", "Finland", "Finland", "Lanh / mat", "Nha co san, van dong deu", "-10 den 20", "Medium", "12-18", "12-15", "Cao", "Cao", "Ga, ca", "Hat, wet", "Ga, ca", "Jerky, dental", "Hat puppy active", "Hat adult active", "Hat senior moderate", "Nha co san"),
    ("Wetterhoun", "Netherlands", "Holland", "Oon doi / mat", "Nha rong, can van dong", "10-22", "Medium", "20-25", "12-14", "Cao", "Cao", "Ga, ca", "Hat, wet", "Ga, ca", "Jerky, chew", "Hat puppy active", "Hat adult active", "Hat senior moderate", "Nha rong"),
    ("Munsterlander", "Germany", "Đức", "Oon doi / mat", "Nha co san, van dong cao", "10-21", "Medium/Large", "18-28", "12-14", "Cao", "Cao", "Ga, bo", "Hat, wet", "Ga, bo", "Jerky, chew", "Hat puppy active", "Hat adult active", "Hat senior moderate", "Nha co san"),
    ("King Charles Spaniel", "United Kingdom", "England", "Oon doi / mat", "Trong nha, can yen tinh", "18-25", "Small", "5-8", "10-14", "Trung binh", "Trung binh", "Ga, ca", "Hat, wet", "Ga, ca", "Soft treat, dental", "Hat puppy small breed", "Hat adult small breed", "Hat senior gentle digest", "Trong nha"),
    ("Brittany", "France", "Phap", "Oon doi / mat", "Nha co san, van dong cao", "10-22", "Medium", "15-20", "12-14", "Cao", "Rất cao", "Ga, ca", "Hat, wet", "Ga, ca", "Jerky, chew", "Hat puppy active", "Hat adult active", "Hat senior moderate", "Nha co san"),
    ("Pointer", "United Kingdom", "England", "Oon doi / mat", "Nha co san, can van dong", "10-22", "Medium/Large", "20-30", "12-14", "Cao", "Rất cao", "Ga, ca", "Hat, wet", "Ga, ca", "Jerky, chew", "Hat puppy active", "Hat adult active", "Hat senior joint support", "Nha co san"),
    ("Plott Hound", "United States", "Mỹ", "Oon doi / mat", "Nha co san, van dong", "10-22", "Medium/Large", "20-30", "10-12", "Cao", "Cao", "Ga, bo", "Hat, wet", "Ga, bo", "Jerky, chew", "Hat puppy active", "Hat adult active", "Hat senior moderate", "Nha co san")
]

extra_cats = [
    ("American Bobtail", "United States", "Mỹ", "Oon doi / mat", "Nha thoang, can tuong tac", "15-25", "Medium", "4-7", "12-15", "Trung binh - cao", "Cao", "Ga, ca", "Hat, wet", "Ga, ca", "Jerky, dental", "Hat kitten active", "Hat adult active", "Hat senior moderate", "Nha thoang"),
    ("Asian", "United Kingdom", "Anh", "Am / on doi", "Trong nha, can quet xep", "18-28", "Medium", "3-5", "10-15", "Trung binh", "Trung binh", "Ga, ca", "Hat, wet", "Ga, ca", "Soft treat", "Hat kitten growth", "Hat adult balanced", "Hat senior moderate", "Trong nha"),
    ("Colorpoint Shorthair", "United States", "Mỹ", "Am / on doi", "Trong nha, yên tinh", "18-28", "Medium", "3-5", "12-15", "Trung binh - cao", "Cao", "Ca, ga", "Hat, wet", "Ca, ga", "Soft treat, dental", "Hat kitten growth", "Hat adult active", "Hat senior moderate", "Trong nha"),
    ("Cheetoh", "United States", "Mỹ", "Am / on doi", "Trong nha, can van dong", "18-28", "Medium/Large", "4-8", "10-15", "Cao", "Rất cao", "Ga, ca", "Hat, wet", "Ga, ca", "Freeze-dried treat", "Hat kitten active", "Hat adult active", "Hat senior lean", "Trong nha"),
    ("European Burmese", "Europe", "Chau Au", "Am / on doi", "Trong nha, gan chu", "18-28", "Medium", "3-6", "10-15", "Cao", "Cao", "Ga, ca", "Hat, wet", "Ga, ca", "Soft treat", "Hat kitten growth", "Hat adult active", "Hat senior moderate", "Trong nha"),
    ("Khao Manee", "Thailand", "Thai Lan", "Am / on doi", "Trong nha, can sang tao", "18-28", "Medium", "3-6", "10-15", "Trung binh", "Trung binh", "Ga, ca", "Hat, wet", "Ga, ca", "Soft treat", "Hat kitten growth", "Hat adult balanced", "Hat senior moderate", "Trong nha"),
    ("Lynx Point", "United States", "Mỹ", "Oon doi / mat", "Trong nha, can doi choi", "15-25", "Medium", "3-6", "10-15", "Trung binh - cao", "Cao", "Ga, ca", "Hat, wet", "Ga, ca", "Freeze-dried treat", "Hat kitten active", "Hat adult active", "Hat senior moderate", "Trong nha"),
    ("Minskin", "United States", "Mỹ", "Am / on doi", "Trong nha, thoang mat", "18-28", "Small/Medium", "2-5", "10-13", "Trung binh", "Trung binh", "Ga, ca", "Hat, wet", "Ga, ca", "Soft treat", "Hat kitten growth", "Hat adult moderate", "Hat senior gentle digest", "Trong nha"),
    ("Nebelung", "United States", "Mỹ", "Oon doi / mat", "Trong nha, yên tinh", "15-25", "Medium", "3-6", "12-15", "Trung binh", "Trung binh", "Ca, ga", "Hat, wet", "Ca, ga", "Soft treat", "Hat kitten growth", "Hat adult moderate", "Hat senior moderate", "Trong nha"),
    ("Peterbald", "Russia", "Nga", "Am / on doi", "Trong nha, gan chu", "18-28", "Medium", "3-6", "10-15", "Cao", "Cao", "Ga, ca", "Hat, wet", "Ga, ca", "Soft treat, dental", "Hat kitten growth", "Hat adult active", "Hat senior moderate", "Trong nha"),
    ("Siberian", "Russia", "Nga", "Lanh / mat", "Nha thoang, can so sanh", "10-22", "Medium/Large", "4-8", "12-15", "Trung binh - cao", "Cao", "Ga, ca", "Hat, wet", "Ga, ca", "Jerky, dental", "Hat kitten growth", "Hat adult active", "Hat senior moderate", "Nha thoang"),
    ("Singapura", "Singapore", "Singapore", "Am / on doi", "Trong nha, can tuong tac", "18-28", "Small", "2-4", "10-15", "Cao", "Cao", "Ga, ca", "Hat, wet", "Ga, ca", "Freeze-dried treat", "Hat kitten active", "Hat adult active", "Hat senior moderate", "Trong nha"),
    ("Somali", "United States", "Mỹ", "Am / on doi", "Trong nha, can tuong tac", "18-28", "Medium", "3-6", "12-15", "Cao", "Cao", "Ca, ga", "Hat, wet", "Ca, ga", "Freeze-dried treat", "Hat kitten active", "Hat adult active", "Hat senior moderate", "Trong nha"),
    ("Thai", "Thailand", "Thai Lan", "Am / on doi", "Trong nha, gan chu", "18-28", "Medium", "3-6", "10-15", "Trung binh", "Trung binh", "Ga, ca", "Hat, wet", "Ga, ca", "Soft treat", "Hat kitten growth", "Hat adult balanced", "Hat senior moderate", "Trong nha")
]

rows = []
for breed in DOGS + extra_dogs:
    rows.append({
        "species": "Chó",
        "breed_name": breed[0],
        "breed_name_en": breed[0],
        "origin_country": breed[1],
        "origin_region": breed[2],
        "climate": breed[3],
        "suitable_environment": breed[4],
        "temperature_range_c": breed[5],
        "size": breed[6],
        "adult_weight_kg": breed[7],
        "lifespan_years": breed[8],
        "activity_level": breed[9],
        "exercise_requirement": breed[10],
        "energy_level": breed[10],
        "protein_preferences": breed[11],
        "texture_preferences": breed[12],
        "flavor_preferences": breed[13],
        "treat_preferences": breed[14],
        "puppy_food": breed[15],
        "adult_food": breed[16],
        "senior_food": breed[17],
        "suitable_home": breed[18],
        "notes": "Du lieu chuan hoa dung cho he thong quan ly thu cung",
    })

for breed in CATS + extra_cats:
    rows.append({
        "species": "Mèo",
        "breed_name": breed[0],
        "breed_name_en": breed[0],
        "origin_country": breed[1],
        "origin_region": breed[2],
        "climate": breed[3],
        "suitable_environment": breed[4],
        "temperature_range_c": breed[5],
        "size": breed[6],
        "adult_weight_kg": breed[7],
        "lifespan_years": breed[8],
        "activity_level": breed[9],
        "exercise_requirement": breed[10],
        "energy_level": breed[10],
        "protein_preferences": breed[11],
        "texture_preferences": breed[12],
        "flavor_preferences": breed[13],
        "treat_preferences": breed[14],
        "puppy_food": breed[15],
        "adult_food": breed[16],
        "senior_food": breed[17],
        "suitable_home": breed[18],
        "notes": "Du lieu chuan hoa dung cho he thong quan ly thu cung",
    })

json_path = out_dir / "breed_catalog_extended.json"
json_path.write_text(json.dumps(rows, ensure_ascii=False, indent=2), encoding="utf-8")

fieldnames = [
    "species","breed_name","breed_name_en","origin_country","origin_region","climate","suitable_environment",
    "temperature_range_c","size","adult_weight_kg","lifespan_years","activity_level","exercise_requirement",
    "energy_level","protein_preferences","texture_preferences","flavor_preferences","treat_preferences",
    "puppy_food","adult_food","senior_food","suitable_home","notes"
]
with (out_dir / "breed_catalog_extended.csv").open("w", newline='', encoding='utf-8') as csvfile:
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()
    for row in rows:
        writer.writerow({k: row.get(k, '') for k in fieldnames})

print("Dog breeds:", sum(1 for r in rows if r['species']=='Chó'))
print("Cat breeds:", sum(1 for r in rows if r['species']=='Mèo'))
print("Exported json ok")
print("Exported csv ok")
